feat(DO-779): Adding toggle for proximity placement group
dodevops/terraform-azure-basics pull request #1
Opened 2021-08-18 08:10 UTC by timdeluxe

2021-08-18 08:16 UTC, dploeger requested changes

2021-08-18 08:16 UTC, dploeger commented on vars.tf
> +variable "proximiy_placement_group" {
There's a typo here. A t is missing. And I'd suggest using the parameter "create_proximity_placement_group" or "manage_"

2021-08-18 09:39 UTC, dploeger approved these changes
We need a major change for this as it will change the resource locator for the proximity placement group

2021-08-20 10:05 UTC, ThomasMinor approved these changes

2021-08-20 11:32 UTC, merged